

## geo 
dataset_path: /data/yuqi/Datasets/Aerial_lifting_data_release/Yingrenshi
ray_altitude_range: [-95, 54]
num_instance_classes: 50
network_type: gpnerf_nr3d
dataset_type: memory_depth_dji
label_name: fusion
use_scaling: False
sampling_mesh_guidance: True
depth_dji_loss: True
wgt_depth_mse_loss: 1
log2_hashmap_size: 22
desired_resolution: 8192
# batch_size=10240
# train_iterations=200000


# ## semantic
# enable_semantic: True
# label_name: 1018_ml_fusion_0.3
# # batch_size=40960
# # train_iterations=200000


# ## instance
# enable_instance: True
# instance_loss_mode=linear_assignment
# instance_name=instances_mask_0.001_depth
# dataset_type=memory_depth_dji_instance_crossview
# # batch_size=16384
# # train_iterations=100000

